# Generated by Django 5.2.16 on 2026-07-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_calendarevent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calendarevent',
            table=None,
        ),
    ]
